package com.hqkang.DSMS.Server;


/**
* com/hqkang/DSMS/Server/ClinicSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

abstract public class ClinicSHelper
{
  private static String  _id = "IDL:com/hqkang/DSMS/Server/ClinicS:1.0";

  public static void insert (org.omg.CORBA.Any a, com.hqkang.DSMS.Server.ClinicS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.hqkang.DSMS.Server.ClinicS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.hqkang.DSMS.Server.ClinicSHelper.id (), "ClinicS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.hqkang.DSMS.Server.ClinicS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClinicSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.hqkang.DSMS.Server.ClinicS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.hqkang.DSMS.Server.ClinicS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.hqkang.DSMS.Server.ClinicS)
      return (com.hqkang.DSMS.Server.ClinicS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.hqkang.DSMS.Server._ClinicSStub stub = new com.hqkang.DSMS.Server._ClinicSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.hqkang.DSMS.Server.ClinicS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.hqkang.DSMS.Server.ClinicS)
      return (com.hqkang.DSMS.Server.ClinicS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.hqkang.DSMS.Server._ClinicSStub stub = new com.hqkang.DSMS.Server._ClinicSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
