package com.hqkang.DSMS.Server;


/**
* com/hqkang/DSMS/Server/ClinicSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Wednesday, June 29, 2016 11:08:18 PM EDT
*/

public abstract class ClinicSPOA extends org.omg.PortableServer.Servant
 implements com.hqkang.DSMS.Server.ClinicSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getSrvURLList", new java.lang.Integer (0));
    _methods.put ("getSrvUDPList", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("createRecord", new java.lang.Integer (3));
    _methods.put ("getSeq", new java.lang.Integer (4));
    _methods.put ("check", new java.lang.Integer (5));
    _methods.put ("editRecord", new java.lang.Integer (6));
    _methods.put ("setSeq", new java.lang.Integer (7));
    _methods.put ("select", new java.lang.Integer (8));
    _methods.put ("remove", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/hqkang/DSMS/Server/ClinicS/getSrvURLList
       {
         com.hqkang.DSMS.Server.ClinicSPackage.MapItem $result[] = null;
         $result = this.getSrvURLList ();
         out = $rh.createReply();
         com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.write (out, $result);
         break;
       }

       case 1:  // com/hqkang/DSMS/Server/ClinicS/getSrvUDPList
       {
         com.hqkang.DSMS.Server.ClinicSPackage.MapItem $result[] = null;
         $result = this.getSrvUDPList ();
         out = $rh.createReply();
         com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.write (out, $result);
         break;
       }

       case 2:  // com/hqkang/DSMS/Server/ClinicS/getRecordCounts
       {
         String AID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (AID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // com/hqkang/DSMS/Server/ClinicS/createRecord
       {
         com.hqkang.DSMS.Server.ClinicSPackage.Record r = com.hqkang.DSMS.Server.ClinicSPackage.RecordHelper.read (in);
         String AID = in.read_string ();
         com.hqkang.DSMS.Server.ClinicSPackage.createRes $result = null;
         $result = this.createRecord (r, AID);
         out = $rh.createReply();
         com.hqkang.DSMS.Server.ClinicSPackage.createResHelper.write (out, $result);
         break;
       }

       case 4:  // com/hqkang/DSMS/Server/ClinicS/getSeq
       {
         int $result = (int)0;
         $result = this.getSeq ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // com/hqkang/DSMS/Server/ClinicS/check
       {
         String key = in.read_string ();
         boolean $result = false;
         $result = this.check (key);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // com/hqkang/DSMS/Server/ClinicS/editRecord
       {
         String RID = in.read_string ();
         String field = in.read_string ();
         String value = in.read_string ();
         String AID = in.read_string ();
         boolean $result = false;
         $result = this.editRecord (RID, field, value, AID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // com/hqkang/DSMS/Server/ClinicS/setSeq
       {
         int s = in.read_long ();
         boolean $result = false;
         $result = this.setSeq (s);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // com/hqkang/DSMS/Server/ClinicS/select
       {
         String RID = in.read_string ();
         com.hqkang.DSMS.Server.ClinicSPackage.Record $result = null;
         $result = this.select (RID);
         out = $rh.createReply();
         com.hqkang.DSMS.Server.ClinicSPackage.RecordHelper.write (out, $result);
         break;
       }

       case 9:  // com/hqkang/DSMS/Server/ClinicS/remove
       {
         String RID = in.read_string ();
         boolean $result = false;
         $result = this.remove (RID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/hqkang/DSMS/Server/ClinicS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClinicS _this() 
  {
    return ClinicSHelper.narrow(
    super._this_object());
  }

  public ClinicS _this(org.omg.CORBA.ORB orb) 
  {
    return ClinicSHelper.narrow(
    super._this_object(orb));
  }


} // class ClinicSPOA
