package com.hqkang.DSMS.Server;


/**
* com/hqkang/DSMS/Server/ClinicS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

public interface ClinicS extends ClinicSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClinicS
