package com.hqkang.DSMS.Server;


/**
* com/hqkang/DSMS/Server/ClinicSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

public interface ClinicSOperations 
{
  com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] getSrvURLList ();
  com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] getSrvUDPList ();
  String getRecordCounts (String AID);
  com.hqkang.DSMS.Server.ClinicSPackage.createRes createRecord (com.hqkang.DSMS.Server.ClinicSPackage.Record r, String AID);
  int getSeq ();
  boolean check (String key);
  boolean editRecord (String RID, String field, String value, String AID);
  boolean setSeq (int s);
  com.hqkang.DSMS.Server.ClinicSPackage.Record select (String RID);
  boolean remove (String RID);
  boolean transferRecord (String RID, String remoteAdd, String AID);
} // interface ClinicSOperations
