package com.hqkang.DSMS.Server;

/**
* com/hqkang/DSMS/Server/ClinicSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

public final class ClinicSHolder implements org.omg.CORBA.portable.Streamable
{
  public com.hqkang.DSMS.Server.ClinicS value = null;

  public ClinicSHolder ()
  {
  }

  public ClinicSHolder (com.hqkang.DSMS.Server.ClinicS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.hqkang.DSMS.Server.ClinicSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.hqkang.DSMS.Server.ClinicSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.hqkang.DSMS.Server.ClinicSHelper.type ();
  }

}
