package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/createResHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Wednesday, June 29, 2016 11:08:18 PM EDT
*/

abstract public class createResHelper
{
  private static String  _id = "IDL:com/hqkang/DSMS/Server/ClinicS/createRes:1.0";

  public static void insert (org.omg.CORBA.Any a, com.hqkang.DSMS.Server.ClinicSPackage.createRes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.createRes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[0] = new org.omg.CORBA.StructMember (
            "res",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "RID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.hqkang.DSMS.Server.ClinicSPackage.createResHelper.id (), "createRes", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.createRes read (org.omg.CORBA.portable.InputStream istream)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.createRes value = new com.hqkang.DSMS.Server.ClinicSPackage.createRes ();
    value.res = istream.read_boolean ();
    value.RID = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.hqkang.DSMS.Server.ClinicSPackage.createRes value)
  {
    ostream.write_boolean (value.res);
    ostream.write_string (value.RID);
  }

}
