package com.hqkang.DSMS.Server.ClinicSPackage;

/**
* com/hqkang/DSMS/Server/ClinicSPackage/createResHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

public final class createResHolder implements org.omg.CORBA.portable.Streamable
{
  public com.hqkang.DSMS.Server.ClinicSPackage.createRes value = null;

  public createResHolder ()
  {
  }

  public createResHolder (com.hqkang.DSMS.Server.ClinicSPackage.createRes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.hqkang.DSMS.Server.ClinicSPackage.createResHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.createResHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.hqkang.DSMS.Server.ClinicSPackage.createResHelper.type ();
  }

}
