package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/HashmapHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

abstract public class HashmapHelper
{
  private static String  _id = "IDL:com/hqkang/DSMS/Server/ClinicS/Hashmap:1.0";

  public static void insert (org.omg.CORBA.Any a, com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.hqkang.DSMS.Server.ClinicSPackage.MapItemHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.id (), "Hashmap", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.MapItem value[] = null;
    int _len0 = istream.read_long ();
    value = new com.hqkang.DSMS.Server.ClinicSPackage.MapItem[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.hqkang.DSMS.Server.ClinicSPackage.MapItemHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.hqkang.DSMS.Server.ClinicSPackage.MapItemHelper.write (ostream, value[_i0]);
  }

}
