package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/HashmapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Wednesday, June 29, 2016 11:08:18 PM EDT
*/

public final class HashmapHolder implements org.omg.CORBA.portable.Streamable
{
  public com.hqkang.DSMS.Server.ClinicSPackage.MapItem value[] = null;

  public HashmapHolder ()
  {
  }

  public HashmapHolder (com.hqkang.DSMS.Server.ClinicSPackage.MapItem[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.hqkang.DSMS.Server.ClinicSPackage.HashmapHelper.type ();
  }

}
