package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/MapItemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

abstract public class MapItemHelper
{
  private static String  _id = "IDL:com/hqkang/DSMS/Server/ClinicS/MapItem:1.0";

  public static void insert (org.omg.CORBA.Any a, com.hqkang.DSMS.Server.ClinicSPackage.MapItem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.MapItem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.hqkang.DSMS.Server.ClinicSPackage.MapItemHelper.id (), "MapItem", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.MapItem read (org.omg.CORBA.portable.InputStream istream)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.MapItem value = new com.hqkang.DSMS.Server.ClinicSPackage.MapItem ();
    value.key = istream.read_string ();
    value.value = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.hqkang.DSMS.Server.ClinicSPackage.MapItem value)
  {
    ostream.write_string (value.key);
    ostream.write_string (value.value);
  }

}
