package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/MapItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Wednesday, June 29, 2016 11:08:18 PM EDT
*/

public final class MapItem implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public MapItem ()
  {
  } // ctor

  public MapItem (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class MapItem
