package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/Record.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Saturday, July 2, 2016 1:03:51 AM EDT
*/

public final class Record implements org.omg.CORBA.portable.IDLEntity
{
  public String recordID = null;
  public String firstName = null;
  public String lastName = null;
  public String designation = null;
  public String status = null;
  public int statusdate = (int)0;
  public String address = null;
  public String phone = null;
  public String specialization = null;
  public String location = null;
  public String _class = null;

  public Record ()
  {
  } // ctor

  public Record (String _recordID, String _firstName, String _lastName, String _designation, String _status, int _statusdate, String _address, String _phone, String _specialization, String _location, String __class)
  {
    recordID = _recordID;
    firstName = _firstName;
    lastName = _lastName;
    designation = _designation;
    status = _status;
    statusdate = _statusdate;
    address = _address;
    phone = _phone;
    specialization = _specialization;
    location = _location;
    _class = __class;
  } // ctor

} // class Record
