package com.hqkang.DSMS.Server.ClinicSPackage;


/**
* com/hqkang/DSMS/Server/ClinicSPackage/RecordHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/kanghuaqiang/git/DSMS/DSMS/src/ClinicServer.idl
* Wednesday, June 29, 2016 11:08:18 PM EDT
*/

abstract public class RecordHelper
{
  private static String  _id = "IDL:com/hqkang/DSMS/Server/ClinicS/Record:1.0";

  public static void insert (org.omg.CORBA.Any a, com.hqkang.DSMS.Server.ClinicSPackage.Record that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.Record extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [10];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "recordID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "firstName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "lastName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "designation",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "statusdate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "address",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "phone",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "specialization",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "location",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.hqkang.DSMS.Server.ClinicSPackage.RecordHelper.id (), "Record", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.hqkang.DSMS.Server.ClinicSPackage.Record read (org.omg.CORBA.portable.InputStream istream)
  {
    com.hqkang.DSMS.Server.ClinicSPackage.Record value = new com.hqkang.DSMS.Server.ClinicSPackage.Record ();
    value.recordID = istream.read_string ();
    value.firstName = istream.read_string ();
    value.lastName = istream.read_string ();
    value.designation = istream.read_string ();
    value.status = istream.read_string ();
    value.statusdate = istream.read_long ();
    value.address = istream.read_string ();
    value.phone = istream.read_string ();
    value.specialization = istream.read_string ();
    value.location = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.hqkang.DSMS.Server.ClinicSPackage.Record value)
  {
    ostream.write_string (value.recordID);
    ostream.write_string (value.firstName);
    ostream.write_string (value.lastName);
    ostream.write_string (value.designation);
    ostream.write_string (value.status);
    ostream.write_long (value.statusdate);
    ostream.write_string (value.address);
    ostream.write_string (value.phone);
    ostream.write_string (value.specialization);
    ostream.write_string (value.location);
  }

}
